require: rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
    - db/schema.rb
Rails:
  Enabled: true

Style/Documentation:
  Enabled: false
Style/StructInheritance:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
Metrics/LineLength:
  Max: 120

RSpec/LetSetup:
  Enabled: false
