default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: ms_shop_server_development

test:
  <<: *default
  database: ms_shop_server_test

production:
  <<: *default
  database: ms_shop_server_production
